<a href="https://colab.research.google.com/github/Ruchika222/GitTutorial/blob/master/Happy_city_data_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [16]:
df=pd.read_csv('happydata.csv')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143 entries, 0 to 142
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   infoavail      143 non-null    int64
 1   housecost      143 non-null    int64
 2   schoolquality  143 non-null    int64
 3   policetrust    143 non-null    int64
 4   streetquality  143 non-null    int64
 5   ëvents         143 non-null    int64
 6   happy          143 non-null    int64
dtypes: int64(7)
memory usage: 7.9 KB


In [18]:
df.head()

infoavail  housecost  schoolquality  policetrust  streetquality  ëvents  \
0          3          3              3            4              2       4   
1          3          2              3            5              4       3   
2          5          3              3            3              3       5   
3          5          4              3            3              3       5   
4          5          4              3            3              3       5   

   happy  
0      0  
1      0  
2      1  
3      0  
4      0

In [19]:
#There are total 143 rows and 7 columns
df.shape

(143, 7)

In [20]:
df.infoavail.unique(),df.housecost.unique(),df.schoolquality.unique(),df.policetrust.unique(),df.streetquality.unique(),df.ëvents.unique(),df.happy.unique()

(array([3, 5, 4, 1]),
 array([3, 2, 4, 5, 1]),
 array([3, 2, 4, 5, 1]),
 array([4, 5, 3, 2, 1]),
 array([2, 4, 3, 5, 1]),
 array([4, 3, 5, 2, 1]),
 array([0, 1]))

In [21]:
df.corr()

infoavail  housecost  schoolquality  policetrust  \
infoavail       1.000000   0.092676       0.301971     0.104378   
housecost       0.092676   1.000000       0.181081     0.107432   
schoolquality   0.301971   0.181081       1.000000     0.298898   
policetrust     0.104378   0.107432       0.298898     1.000000   
streetquality   0.399203  -0.002141       0.329874     0.269420   
ëvents          0.417521   0.024546       0.207006     0.199151   
happy           0.312740   0.019368       0.163639     0.113356   

               streetquality    ëvents     happy  
infoavail           0.399203  0.417521  0.312740  
housecost          -0.002141  0.024546  0.019368  
schoolquality       0.329874  0.207006  0.163639  
policetrust         0.269420  0.199151  0.113356  
streetquality       1.000000  0.307402  0.206685  
ëvents              0.307402  1.000000  0.220729  
happy               0.206685  0.220729  1.000000

In [22]:
x=df[['infoavail','schoolquality','policetrust','streetquality','ëvents']]
y = df['happy']

In [23]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [24]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((114, 5), (29, 5), (114,), (29,))

In [25]:
from sklearn.svm import SVC

In [26]:
model = SVC()

In [27]:
m=model.fit(x_train,y_train)

In [28]:
y_hat=m.predict(x_test)

In [29]:
y_hat

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0])

In [30]:
from sklearn.metrics import confusion_matrix

In [31]:
confusion_matrix(y_test,y_hat)

array([[ 5,  9],
       [ 5, 10]])

In [32]:
from sklearn.metrics import accuracy_score

In [33]:
#SVc give 51% accuracy
accuracy_score(y_test,y_hat)

0.5172413793103449

In [34]:
from sklearn.linear_model import LogisticRegression

In [35]:
model1=LogisticRegression()

In [36]:
m=model1.fit(x_train,y_train)

In [37]:
y_hat1=m.predict(x_test)

In [38]:
from sklearn.metrics import accuracy_score

In [39]:
#Logistic Regression gives 58%
accuracy_score(y_test,y_hat1)

0.5862068965517241

In [40]:
#KNN Classifier

In [41]:
from sklearn.neighbors import KNeighborsClassifier

In [42]:
model=KNeighborsClassifier()

In [43]:
m=model.fit(x_train,y_train)

In [44]:
y_hat=m.predict(x_test)

In [45]:
y_hat

array([1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0])

In [46]:
accuracy_score(y_test,y_hat)

0.4827586206896552